/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HimsApiClient);
  }
}(this, function(expect, HimsApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HimsApiClient.AuthenticationControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AuthenticationControllerApi', function() {
    describe('authenticationControllerAuth', function() {
      it('should call authenticationControllerAuth successfully', function(done) {
        //uncomment below and update the code to test authenticationControllerAuth
        //instance.authenticationControllerAuth(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authenticationControllerCheckLogin', function() {
      it('should call authenticationControllerCheckLogin successfully', function(done) {
        //uncomment below and update the code to test authenticationControllerCheckLogin
        //instance.authenticationControllerCheckLogin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authenticationControllerSessionLogin', function() {
      it('should call authenticationControllerSessionLogin successfully', function(done) {
        //uncomment below and update the code to test authenticationControllerSessionLogin
        //instance.authenticationControllerSessionLogin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authenticationControllerToken', function() {
      it('should call authenticationControllerToken successfully', function(done) {
        //uncomment below and update the code to test authenticationControllerToken
        //instance.authenticationControllerToken(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
