/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HimsApiClient);
  }
}(this, function(expect, HimsApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HimsApiClient.DoctorControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DoctorControllerApi', function() {
    describe('doctorControllerCount', function() {
      it('should call doctorControllerCount successfully', function(done) {
        //uncomment below and update the code to test doctorControllerCount
        //instance.doctorControllerCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('doctorControllerCreate', function() {
      it('should call doctorControllerCreate successfully', function(done) {
        //uncomment below and update the code to test doctorControllerCreate
        //instance.doctorControllerCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('doctorControllerDeleteById', function() {
      it('should call doctorControllerDeleteById successfully', function(done) {
        //uncomment below and update the code to test doctorControllerDeleteById
        //instance.doctorControllerDeleteById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('doctorControllerFind', function() {
      it('should call doctorControllerFind successfully', function(done) {
        //uncomment below and update the code to test doctorControllerFind
        //instance.doctorControllerFind(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('doctorControllerFindById', function() {
      it('should call doctorControllerFindById successfully', function(done) {
        //uncomment below and update the code to test doctorControllerFindById
        //instance.doctorControllerFindById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('doctorControllerReplaceById', function() {
      it('should call doctorControllerReplaceById successfully', function(done) {
        //uncomment below and update the code to test doctorControllerReplaceById
        //instance.doctorControllerReplaceById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('doctorControllerUpdateAll', function() {
      it('should call doctorControllerUpdateAll successfully', function(done) {
        //uncomment below and update the code to test doctorControllerUpdateAll
        //instance.doctorControllerUpdateAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('doctorControllerUpdateById', function() {
      it('should call doctorControllerUpdateById successfully', function(done) {
        //uncomment below and update the code to test doctorControllerUpdateById
        //instance.doctorControllerUpdateById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
