/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HimsApiClient);
  }
}(this, function(expect, HimsApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HimsApiClient.Icd10ControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Icd10ControllerApi', function() {
    describe('icd10ControllerCount', function() {
      it('should call icd10ControllerCount successfully', function(done) {
        //uncomment below and update the code to test icd10ControllerCount
        //instance.icd10ControllerCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('icd10ControllerCreate', function() {
      it('should call icd10ControllerCreate successfully', function(done) {
        //uncomment below and update the code to test icd10ControllerCreate
        //instance.icd10ControllerCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('icd10ControllerDeleteById', function() {
      it('should call icd10ControllerDeleteById successfully', function(done) {
        //uncomment below and update the code to test icd10ControllerDeleteById
        //instance.icd10ControllerDeleteById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('icd10ControllerFind', function() {
      it('should call icd10ControllerFind successfully', function(done) {
        //uncomment below and update the code to test icd10ControllerFind
        //instance.icd10ControllerFind(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('icd10ControllerFindById', function() {
      it('should call icd10ControllerFindById successfully', function(done) {
        //uncomment below and update the code to test icd10ControllerFindById
        //instance.icd10ControllerFindById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('icd10ControllerReplaceById', function() {
      it('should call icd10ControllerReplaceById successfully', function(done) {
        //uncomment below and update the code to test icd10ControllerReplaceById
        //instance.icd10ControllerReplaceById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('icd10ControllerUpdateAll', function() {
      it('should call icd10ControllerUpdateAll successfully', function(done) {
        //uncomment below and update the code to test icd10ControllerUpdateAll
        //instance.icd10ControllerUpdateAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('icd10ControllerUpdateById', function() {
      it('should call icd10ControllerUpdateById successfully', function(done) {
        //uncomment below and update the code to test icd10ControllerUpdateById
        //instance.icd10ControllerUpdateById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
