/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HimsApiClient);
  }
}(this, function(expect, HimsApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HimsApiClient.PolicyControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PolicyControllerApi', function() {
    describe('policyControllerCount', function() {
      it('should call policyControllerCount successfully', function(done) {
        //uncomment below and update the code to test policyControllerCount
        //instance.policyControllerCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('policyControllerCreate', function() {
      it('should call policyControllerCreate successfully', function(done) {
        //uncomment below and update the code to test policyControllerCreate
        //instance.policyControllerCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('policyControllerDeleteById', function() {
      it('should call policyControllerDeleteById successfully', function(done) {
        //uncomment below and update the code to test policyControllerDeleteById
        //instance.policyControllerDeleteById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('policyControllerFind', function() {
      it('should call policyControllerFind successfully', function(done) {
        //uncomment below and update the code to test policyControllerFind
        //instance.policyControllerFind(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('policyControllerFindById', function() {
      it('should call policyControllerFindById successfully', function(done) {
        //uncomment below and update the code to test policyControllerFindById
        //instance.policyControllerFindById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('policyControllerReplaceById', function() {
      it('should call policyControllerReplaceById successfully', function(done) {
        //uncomment below and update the code to test policyControllerReplaceById
        //instance.policyControllerReplaceById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('policyControllerUpdateAll', function() {
      it('should call policyControllerUpdateAll successfully', function(done) {
        //uncomment below and update the code to test policyControllerUpdateAll
        //instance.policyControllerUpdateAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('policyControllerUpdateById', function() {
      it('should call policyControllerUpdateById successfully', function(done) {
        //uncomment below and update the code to test policyControllerUpdateById
        //instance.policyControllerUpdateById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
