/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HimsApiClient);
  }
}(this, function(expect, HimsApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HimsApiClient.RoleControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RoleControllerApi', function() {
    describe('roleControllerCount', function() {
      it('should call roleControllerCount successfully', function(done) {
        //uncomment below and update the code to test roleControllerCount
        //instance.roleControllerCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('roleControllerCreate', function() {
      it('should call roleControllerCreate successfully', function(done) {
        //uncomment below and update the code to test roleControllerCreate
        //instance.roleControllerCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('roleControllerDeleteById', function() {
      it('should call roleControllerDeleteById successfully', function(done) {
        //uncomment below and update the code to test roleControllerDeleteById
        //instance.roleControllerDeleteById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('roleControllerFind', function() {
      it('should call roleControllerFind successfully', function(done) {
        //uncomment below and update the code to test roleControllerFind
        //instance.roleControllerFind(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('roleControllerFindById', function() {
      it('should call roleControllerFindById successfully', function(done) {
        //uncomment below and update the code to test roleControllerFindById
        //instance.roleControllerFindById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('roleControllerReplaceById', function() {
      it('should call roleControllerReplaceById successfully', function(done) {
        //uncomment below and update the code to test roleControllerReplaceById
        //instance.roleControllerReplaceById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('roleControllerUpdateAll', function() {
      it('should call roleControllerUpdateAll successfully', function(done) {
        //uncomment below and update the code to test roleControllerUpdateAll
        //instance.roleControllerUpdateAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('roleControllerUpdateById', function() {
      it('should call roleControllerUpdateById successfully', function(done) {
        //uncomment below and update the code to test roleControllerUpdateById
        //instance.roleControllerUpdateById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
