/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HimsApiClient);
  }
}(this, function(expect, HimsApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HimsApiClient.UserControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserControllerApi', function() {
    describe('userControllerCount', function() {
      it('should call userControllerCount successfully', function(done) {
        //uncomment below and update the code to test userControllerCount
        //instance.userControllerCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userControllerCreate', function() {
      it('should call userControllerCreate successfully', function(done) {
        //uncomment below and update the code to test userControllerCreate
        //instance.userControllerCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userControllerDeleteById', function() {
      it('should call userControllerDeleteById successfully', function(done) {
        //uncomment below and update the code to test userControllerDeleteById
        //instance.userControllerDeleteById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userControllerFind', function() {
      it('should call userControllerFind successfully', function(done) {
        //uncomment below and update the code to test userControllerFind
        //instance.userControllerFind(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userControllerFindById', function() {
      it('should call userControllerFindById successfully', function(done) {
        //uncomment below and update the code to test userControllerFindById
        //instance.userControllerFindById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userControllerPrintCurrentUser', function() {
      it('should call userControllerPrintCurrentUser successfully', function(done) {
        //uncomment below and update the code to test userControllerPrintCurrentUser
        //instance.userControllerPrintCurrentUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userControllerReplaceById', function() {
      it('should call userControllerReplaceById successfully', function(done) {
        //uncomment below and update the code to test userControllerReplaceById
        //instance.userControllerReplaceById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userControllerUpdateAll', function() {
      it('should call userControllerUpdateAll successfully', function(done) {
        //uncomment below and update the code to test userControllerUpdateAll
        //instance.userControllerUpdateAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userControllerUpdateById', function() {
      it('should call userControllerUpdateById successfully', function(done) {
        //uncomment below and update the code to test userControllerUpdateById
        //instance.userControllerUpdateById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
