stages:
  - fetch
  - build
  - deploy


fetch_dev:
  stage: fetch
  tags:
    - hims-app
  variables:
    GIT_STRATEGY: fetch
    GIT_CLONE_PATH: /home/bitnami/builds/hims-app-dev
  script:
    - echo "This job fetches hims_app dev branch. "
    - echo "pulling submodules"
    - ssh-agent ~/.scripts/submod_update.sh dev
    - cd /home/bitnami/builds/hims-app-dev
    - echo "Ensure all node modules are updated and available"
    - cp config/dev.env .env
    - yarn install
  only:
    refs:
      - hims-app
    changes:
      - package.json

build_dev:
  stage: build
  variables:
    GIT_STRATEGY: none
  tags:
    - hims-app
  needs: ["fetch_dev"]
  script:
    - echo "This job builds hims-dev after fetch_dev"
    - cd /home/bitnami/builds/hims-app-dev
    - printenv CURRENT_VERSION
    - yarn build
  only:
    refs:
      - hims-app
    changes:
      - package.json



deploy_dev:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  tags:
    - hims-app
  needs: ["build_dev"]
  script:
    - echo "Needs hims-dev to have passed build stage"
    - cd /home/bitnami/builds/hims-app-dev
    - echo "Deploy the hims-dev"
    - printenv CURRENT_VERSION
    - yarn run publish
  only:
    refs:
      - hims-app
    changes:
      - package.json


