stages:
  - fetch
  - build
  - deploy
  - sync


fetch_dev:
  stage: fetch
  tags:
    - dev-2
  variables:
    GIT_STRATEGY: fetch
    GIT_CLONE_PATH: /home/bitnami/builds/hims-app-dev-2
  script:
    - echo "This job fetches hims_app dev branch. "
    - whoami
    - node -v
    - echo "pulling submodules"
    - ssh-agent ~/.scripts/submod_update.sh dev2
    - echo "Ensure all node modules are updated and available"
    - cp config/dev2.env .env
    - yarn install
  only:
    refs:
      - dev-2
    changes:
      - package.json

build_dev:
  stage: build
  variables:
    GIT_STRATEGY: none
  tags:
    - dev-2
  needs: ["fetch_dev"]
  script:
    - echo "This job builds hims-dev-2 after fetch_dev"
    - cd /home/bitnami/builds/hims-app-dev-2
  only:
    refs:
      - dev-2
    changes:
      - package.json



deploy_dev:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  tags:
    - dev-2
  needs: ["build_dev"]
  script:
    - echo "Needs hims-dev-2 to have passed build stage"
    - cd /home/bitnami/builds/hims-app-dev-2
    - echo "Deploy the hims-dev-2"
    - printenv CURRENT_VERSION
    - yarn run publish
    - echo "Build on ProcessMaker DevServer"
  only:
    refs:
      - dev-2
    changes:
      - package.json

sync_dev:
  stage: sync
  variables:
    GIT_STRATEGY: none
  tags:
    - dev-2
  needs: ["deploy_dev"]
  script:
    - echo "Syncing Web Application for DEV2"
    - rm -rf /tmp/dev2.tar
    - cd /home/bitnami/builds/hims-app-dev-2
    - tar cvf /tmp/dev2.tar ./build
  only:
    refs:
      - dev-2
    changes:
      - package.json
