stages:
  - fetch
  - build
  - deploy


fetch_dev:
  stage: fetch
  script:
    - echo "This job fetches hims_app dev branch. "
    - echo "Runs first"

fetch_uat:
  stage: fetch
  script:
    - echo "This job fetches hims_app UAT branch."
    - echo "It will start at about the same time as fetch_dev."

build_dev:
  stage: build
  needs: fetch_dev
  script:
    - echo "This job builds hims-dev after fetch_dev"

build_uat:
  stage: build
  needs: fetch_uat
  script:
    - echo "This job builds hims-desktop after fetch_uat"


deploy_dev:
  stage: deploy
  needs: build_dev
  script:
    - echo "Deploy the hims-dev"
    - echo "Needs hims-dev to have passed build stage"

deploy_uat:
  stage: deploy
  needs: build_uat
  script:
    - echo "Deploy the UAT"
    - echo "Needs UAT to have passed build stage"

