stages:
  - fetch
  - build
  - deploy
  - sync


fetch_dev:
  stage: fetch
  tags:
    - hims-app
  variables:
    GIT_STRATEGY: fetch
    GIT_CLONE_PATH: /home/bitnami/builds/hims-app-dev
  script:
    - echo "This job fetches hims_app dev branch. "
    - echo "pulling submodules"
    - ssh-agent ~/.scripts/submod_update.sh dev
    - cd /home/bitnami/builds/hims-app-dev
    - echo "Ensure all node modules are updated and available"
    - cp config/dev.env .env
    - yarn install
  only:
    refs:
      - dev
    changes:
      - package.json

build_dev:
  stage: build
  variables:
    GIT_STRATEGY: none
  tags:
    - hims-app
  needs: ["fetch_dev"]
  script:
    - echo "This job builds hims-dev after fetch_dev"
    - cd /home/bitnami/builds/hims-app-dev
    - printenv CURRENT_VERSION
    - yarn build
  only:
    refs:
      - dev
    changes:
      - package.json



deploy_dev:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  tags:
    - hims-app
  needs: ["build_dev"]
  script:
    - echo "Needs hims-dev to have passed build stage"
    - cd /home/bitnami/builds/hims-app-dev
    - echo "Deploy the hims-dev"
    - printenv CURRENT_VERSION
    - yarn run publish
    - echo "Build on ProcessMaker DevServer"
  only:
    refs:
      - dev
    changes:
      - package.json



sync_dev:
  stage: sync
  when: manual
  variables:
    GIT_STRATEGY: none
  tags:
    - hims-app
  needs: ["deploy_dev"]
  script:
    - rsync -e 'ssh -p 8152' -avHl /home/bitnami/builds/hims-app-dev/build/*  himsapp@18.138.94.224:/hims/hims-app
    - echo "RSync to hims-app API Server"
  only:
    refs:
      - dev
    changes:
      - package.json
