stages:
  - fetch
  - build
  - hardening
  - deploy
  - sync


fetch_dev:
  stage: fetch
  tags:
    - dev-2
  variables:
    GIT_STRATEGY: fetch
    GIT_CLONE_PATH: /home/bitnami/builds/hims-app-dev-2
  script:
    - echo "This job fetches hims_app dev branch. "
    - whoami
    - nvm use v10.17.0
    - nvm alias default v10.17.0
    - echo "pulling submodules"
    - ssh-agent ~/.scripts/submod_update.sh dev2
    - echo "Ensure all node modules are updated and available"
    - cp config/dev2.env .env
    - yarn install --ignore-engines
  only:
    refs:
      - dev-2
    changes:
      - package.json

build_dev:
  stage: build
  variables:
    GIT_STRATEGY: none
  tags:
    - dev-2
  needs: ["fetch_dev"]
  script:
    - echo "This job builds hims-dev-2 after fetch_dev"
    - cd /home/bitnami/builds/hims-app-dev-2
    - yarn build
  only:
    refs:
      - dev-2
    changes:
      - package.json

secure_dev:
  stage: hardening
  variables:
    GIT_STRATEGY: none
  tags:
    - dev-2
  needs: ["build_dev"]
  script:
    - echo "Securing The Application"
    - cd /home/bitnami/builds/hims-app-dev-2
    - printenv CURRENT_VERSION
    - echo "Obfuscate files"
    - echo "Done securing the application"
  only:
    refs:
      - dev-2
    changes:
      - package.json

deploy_dev:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  tags:
    - dev-2
  needs: ["secure_dev"]
  script:
    - echo "Needs hims-dev-2 to have passed build stage"
    - cd /home/bitnami/builds/hims-app-dev-2
    - echo "Deploy the hims-dev-2"
    - printenv CURRENT_VERSION
    - npx electron-builder --win --prepackaged dist/win-unpacked --publish always
    - echo "Build on ProcessMaker DevServer Completed"
    - echo "Prepare websync.."
    - rm -rf ~/builds/dev2.tar
    - tar cvf ~/builds/dev2.tar ./build
    - cd ~/builds
    - echo "Prepare websync.."
  only:
    refs:
      - dev-2
    changes:
      - package.json

sync_dev:
  stage: sync
  variables:
    GIT_STRATEGY: none
  tags:
    - dev-2
  needs: ["deploy_dev"]
  script:
    - echo "Syncing Web Application for DEV2"
    - cd /hims/
    - rm -rf dev.tar hims-app
    - mv /tmp/dev2.tar ./
    - rm -rf hims-app
    - tar -xvf dev2.tar
    - mv build ./hims-app
    - rm -rf dev2.tar
    - ls -al
    - cd /home/bitnami/builds/hims-app-dev-2
    - rm -rf /tmp/dev2.tar
    - tar cvf /tmp/dev2.tar ./build
    - echo "Done Syncing Web Application"
  only:
    refs:
      - dev-2
    changes:
      - package.json
