stages:
  - fetch
  - build
  - deploy


fetch_uat:
  stage: fetch
  tags:
    - uat
  variables:
    GIT_STRATEGY: fetch
    GIT_CLONE_PATH: /home/bitnami/builds/hims-app-uat
  script:
    - echo "This job fetches hims_app uat branch. "
    - cd /home/bitnami/builds/hims-app-uat
    - echo "Ensure all node modules are updated and available"
    - echo "pulling submodules"
    - ssh-agent ~/.scripts/submod_update.sh uat
    - cp config/uat.env .env
    - yarn install
  only:
    refs:
      - uat
    changes:
      - package.json

build_uat:
  stage: build
  variables:
    GIT_STRATEGY: none
  tags:
    - uat
  needs: ["fetch_uat"]
  script:
    - echo "This job builds hims-uat after fetch_uat"
    - cd /home/bitnami/builds/hims-app-uat
    - printenv CURRENT_VERSION
    - yarn build
  only:
    refs:
      - uat
    changes:
      - package.json

deploy_uat:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  tags:
    - uat
  needs: ["build_uat"]
  script:
    - echo "Needs hims-uat to have passed build stage"
    - cd /home/bitnami/builds/hims-app-uat
    - echo "Deploy the hims-uat"
    - printenv CURRENT_VERSION
    - yarn run publish
  only:
    refs:
      - uat
    changes:
      - package.json



