stages:
  - fetch
  - build
  - deploy
  - sync
  - codereview


fetch_uat:
  stage: fetch
  tags:
    - hims-app-builds-uat
  variables:
    GIT_STRATEGY: fetch
    GIT_CLONE_PATH: /home/bitnami/builds/hims-app-uat
  script:
    - echo "This job fetches hims_app uat branch. "
    - cd /home/bitnami/builds/hims-app-uat
    - echo "Ensure all node modules are updated and available"
    - echo "pulling submodules"
    - ssh-agent ~/.scripts/submod_update.sh uat
    - cp config/uat.env .env
    - yarn install
  only:
    refs:
      - uat
    changes:
      - package.json

build_uat:
  stage: build
  variables:
    GIT_STRATEGY: none
  tags:
    - hims-app-builds-uat
  needs: ["fetch_uat"]
  script:
    - echo "This job builds hims-uat after fetch_uat"
    - cd /home/bitnami/builds/hims-app-uat
    - printenv CURRENT_VERSION
    - echo "yarn build skipped - build via yarn run publish"
    - echo "clearing the build folder"
    - rm -rf build/*
  only:
    refs:
      - uat
    changes:
      - package.json

deploy_uat:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  tags:
    - hims-app-builds-uat
  needs: ["build_uat"]
  script:
    - echo "Needs hims-uat to have passed build stage"
    - cd /home/bitnami/builds/hims-app-uat
    - echo "Deploy the hims-uat"
    - printenv CURRENT_VERSION
    - yarn run publish
  only:
    refs:
      - uat
    changes:
      - package.json

build_web_sync:
  stage: sync
  variables:
    GIT_STRATEGY: none
  tags:
    - uat-intellicare
  needs: ["deploy_uat"]
  script:
    - echo "himsapp build to UAT API Server"
    - chmod 600 /home/himsadmin/himsapp-websync.sh
    - bash /home/himsadmin/himsapp-websync.sh
  only:
    refs:
      - uat
    changes:
      - package.json

code_review:
  stage: codereview
  tags:
    - hims-app-builds-uat
  needs: ['build_web_sync']
  script:
    - /usr/local/bin/cr_uat.sh
  only:
    refs:
      - uat
    changes:
      - package.json
