/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Assignment from './model/Assignment';
import BaseBenefitComment from './model/BaseBenefitComment';
import BaseBenefitPlan from './model/BaseBenefitPlan';
import BaseBenefitRevision from './model/BaseBenefitRevision';
import BasebenefitplansCommentsFields from './model/BasebenefitplansCommentsFields';
import BasebenefitplansFields from './model/BasebenefitplansFields';
import BasebenefitplansRevisionsFields from './model/BasebenefitplansRevisionsFields';
import BenefitComment from './model/BenefitComment';
import BenefitLayer from './model/BenefitLayer';
import BenefitLimit from './model/BenefitLimit';
import BenefitPlan from './model/BenefitPlan';
import BenefitRevision from './model/BenefitRevision';
import BenefitplansIoPdfFields from './model/BenefitplansIoPdfFields';
import CanAvailRequest from './model/CanAvailRequest';
import CanAvailResponse from './model/CanAvailResponse';
import CanAvailResponseCoverage from './model/CanAvailResponseCoverage';
import Client from './model/Client';
import ClientsFields from './model/ClientsFields';
import ContactAddress from './model/ContactAddress';
import ContactAddress1 from './model/ContactAddress1';
import ContactNumber from './model/ContactNumber';
import ContactPerson from './model/ContactPerson';
import Cpt from './model/Cpt';
import CptPartial from './model/CptPartial';
import CptsFields from './model/CptsFields';
import CreateProposalRequest from './model/CreateProposalRequest';
import Doctor from './model/Doctor';
import DoctorPartial from './model/DoctorPartial';
import DoctorsFields from './model/DoctorsFields';
import FacilitiesFields from './model/FacilitiesFields';
import Facility from './model/Facility';
import FacilityPartial from './model/FacilityPartial';
import FileAttachment from './model/FileAttachment';
import Filter from './model/Filter';
import Filter1 from './model/Filter1';
import Filter10 from './model/Filter10';
import Filter11 from './model/Filter11';
import Filter12 from './model/Filter12';
import Filter13 from './model/Filter13';
import Filter14 from './model/Filter14';
import Filter15 from './model/Filter15';
import Filter2 from './model/Filter2';
import Filter3 from './model/Filter3';
import Filter4 from './model/Filter4';
import Filter5 from './model/Filter5';
import Filter6 from './model/Filter6';
import Filter7 from './model/Filter7';
import Filter8 from './model/Filter8';
import Filter9 from './model/Filter9';
import Icd10 from './model/Icd10';
import Icd10Partial from './model/Icd10Partial';
import Icd10codesFields from './model/Icd10codesFields';
import InlineResponse200 from './model/InlineResponse200';
import InlineResponse2001 from './model/InlineResponse2001';
import Member from './model/Member';
import MembersFields from './model/MembersFields';
import PoliciesFields from './model/PoliciesFields';
import Policy from './model/Policy';
import Role from './model/Role';
import RolesFields from './model/RolesFields';
import User from './model/User';
import UsersFields from './model/UsersFields';
import AuthenticationControllerApi from './api/AuthenticationControllerApi';
import CptControllerApi from './api/CptControllerApi';
import DoctorControllerApi from './api/DoctorControllerApi';
import FacilityControllerApi from './api/FacilityControllerApi';
import Icd10ControllerApi from './api/Icd10ControllerApi';
import MemberControllerApi from './api/MemberControllerApi';
import PolicyControllerApi from './api/PolicyControllerApi';
import RoleControllerApi from './api/RoleControllerApi';
import UnderwritingBenefitsApi from './api/UnderwritingBenefitsApi';
import UnderwritingClientsApi from './api/UnderwritingClientsApi';
import UnderwritingContractsApi from './api/UnderwritingContractsApi';
import UserControllerApi from './api/UserControllerApi';


/**
* HIMS_API_Defintions_for_Client_Subsystem.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var @HimsApi = require('index'); // See note below*.
* var xxxSvc = new @HimsApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new @HimsApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new @HimsApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new @HimsApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Assignment model constructor.
     * @property {module:model/Assignment}
     */
    Assignment,

    /**
     * The BaseBenefitComment model constructor.
     * @property {module:model/BaseBenefitComment}
     */
    BaseBenefitComment,

    /**
     * The BaseBenefitPlan model constructor.
     * @property {module:model/BaseBenefitPlan}
     */
    BaseBenefitPlan,

    /**
     * The BaseBenefitRevision model constructor.
     * @property {module:model/BaseBenefitRevision}
     */
    BaseBenefitRevision,

    /**
     * The BasebenefitplansCommentsFields model constructor.
     * @property {module:model/BasebenefitplansCommentsFields}
     */
    BasebenefitplansCommentsFields,

    /**
     * The BasebenefitplansFields model constructor.
     * @property {module:model/BasebenefitplansFields}
     */
    BasebenefitplansFields,

    /**
     * The BasebenefitplansRevisionsFields model constructor.
     * @property {module:model/BasebenefitplansRevisionsFields}
     */
    BasebenefitplansRevisionsFields,

    /**
     * The BenefitComment model constructor.
     * @property {module:model/BenefitComment}
     */
    BenefitComment,

    /**
     * The BenefitLayer model constructor.
     * @property {module:model/BenefitLayer}
     */
    BenefitLayer,

    /**
     * The BenefitLimit model constructor.
     * @property {module:model/BenefitLimit}
     */
    BenefitLimit,

    /**
     * The BenefitPlan model constructor.
     * @property {module:model/BenefitPlan}
     */
    BenefitPlan,

    /**
     * The BenefitRevision model constructor.
     * @property {module:model/BenefitRevision}
     */
    BenefitRevision,

    /**
     * The BenefitplansIoPdfFields model constructor.
     * @property {module:model/BenefitplansIoPdfFields}
     */
    BenefitplansIoPdfFields,

    /**
     * The CanAvailRequest model constructor.
     * @property {module:model/CanAvailRequest}
     */
    CanAvailRequest,

    /**
     * The CanAvailResponse model constructor.
     * @property {module:model/CanAvailResponse}
     */
    CanAvailResponse,

    /**
     * The CanAvailResponseCoverage model constructor.
     * @property {module:model/CanAvailResponseCoverage}
     */
    CanAvailResponseCoverage,

    /**
     * The Client model constructor.
     * @property {module:model/Client}
     */
    Client,

    /**
     * The ClientsFields model constructor.
     * @property {module:model/ClientsFields}
     */
    ClientsFields,

    /**
     * The ContactAddress model constructor.
     * @property {module:model/ContactAddress}
     */
    ContactAddress,

    /**
     * The ContactAddress1 model constructor.
     * @property {module:model/ContactAddress1}
     */
    ContactAddress1,

    /**
     * The ContactNumber model constructor.
     * @property {module:model/ContactNumber}
     */
    ContactNumber,

    /**
     * The ContactPerson model constructor.
     * @property {module:model/ContactPerson}
     */
    ContactPerson,

    /**
     * The Cpt model constructor.
     * @property {module:model/Cpt}
     */
    Cpt,

    /**
     * The CptPartial model constructor.
     * @property {module:model/CptPartial}
     */
    CptPartial,

    /**
     * The CptsFields model constructor.
     * @property {module:model/CptsFields}
     */
    CptsFields,

    /**
     * The CreateProposalRequest model constructor.
     * @property {module:model/CreateProposalRequest}
     */
    CreateProposalRequest,

    /**
     * The Doctor model constructor.
     * @property {module:model/Doctor}
     */
    Doctor,

    /**
     * The DoctorPartial model constructor.
     * @property {module:model/DoctorPartial}
     */
    DoctorPartial,

    /**
     * The DoctorsFields model constructor.
     * @property {module:model/DoctorsFields}
     */
    DoctorsFields,

    /**
     * The FacilitiesFields model constructor.
     * @property {module:model/FacilitiesFields}
     */
    FacilitiesFields,

    /**
     * The Facility model constructor.
     * @property {module:model/Facility}
     */
    Facility,

    /**
     * The FacilityPartial model constructor.
     * @property {module:model/FacilityPartial}
     */
    FacilityPartial,

    /**
     * The FileAttachment model constructor.
     * @property {module:model/FileAttachment}
     */
    FileAttachment,

    /**
     * The Filter model constructor.
     * @property {module:model/Filter}
     */
    Filter,

    /**
     * The Filter1 model constructor.
     * @property {module:model/Filter1}
     */
    Filter1,

    /**
     * The Filter10 model constructor.
     * @property {module:model/Filter10}
     */
    Filter10,

    /**
     * The Filter11 model constructor.
     * @property {module:model/Filter11}
     */
    Filter11,

    /**
     * The Filter12 model constructor.
     * @property {module:model/Filter12}
     */
    Filter12,

    /**
     * The Filter13 model constructor.
     * @property {module:model/Filter13}
     */
    Filter13,

    /**
     * The Filter14 model constructor.
     * @property {module:model/Filter14}
     */
    Filter14,

    /**
     * The Filter15 model constructor.
     * @property {module:model/Filter15}
     */
    Filter15,

    /**
     * The Filter2 model constructor.
     * @property {module:model/Filter2}
     */
    Filter2,

    /**
     * The Filter3 model constructor.
     * @property {module:model/Filter3}
     */
    Filter3,

    /**
     * The Filter4 model constructor.
     * @property {module:model/Filter4}
     */
    Filter4,

    /**
     * The Filter5 model constructor.
     * @property {module:model/Filter5}
     */
    Filter5,

    /**
     * The Filter6 model constructor.
     * @property {module:model/Filter6}
     */
    Filter6,

    /**
     * The Filter7 model constructor.
     * @property {module:model/Filter7}
     */
    Filter7,

    /**
     * The Filter8 model constructor.
     * @property {module:model/Filter8}
     */
    Filter8,

    /**
     * The Filter9 model constructor.
     * @property {module:model/Filter9}
     */
    Filter9,

    /**
     * The Icd10 model constructor.
     * @property {module:model/Icd10}
     */
    Icd10,

    /**
     * The Icd10Partial model constructor.
     * @property {module:model/Icd10Partial}
     */
    Icd10Partial,

    /**
     * The Icd10codesFields model constructor.
     * @property {module:model/Icd10codesFields}
     */
    Icd10codesFields,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The Member model constructor.
     * @property {module:model/Member}
     */
    Member,

    /**
     * The MembersFields model constructor.
     * @property {module:model/MembersFields}
     */
    MembersFields,

    /**
     * The PoliciesFields model constructor.
     * @property {module:model/PoliciesFields}
     */
    PoliciesFields,

    /**
     * The Policy model constructor.
     * @property {module:model/Policy}
     */
    Policy,

    /**
     * The Role model constructor.
     * @property {module:model/Role}
     */
    Role,

    /**
     * The RolesFields model constructor.
     * @property {module:model/RolesFields}
     */
    RolesFields,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UsersFields model constructor.
     * @property {module:model/UsersFields}
     */
    UsersFields,

    /**
    * The AuthenticationControllerApi service constructor.
    * @property {module:api/AuthenticationControllerApi}
    */
    AuthenticationControllerApi,

    /**
    * The CptControllerApi service constructor.
    * @property {module:api/CptControllerApi}
    */
    CptControllerApi,

    /**
    * The DoctorControllerApi service constructor.
    * @property {module:api/DoctorControllerApi}
    */
    DoctorControllerApi,

    /**
    * The FacilityControllerApi service constructor.
    * @property {module:api/FacilityControllerApi}
    */
    FacilityControllerApi,

    /**
    * The Icd10ControllerApi service constructor.
    * @property {module:api/Icd10ControllerApi}
    */
    Icd10ControllerApi,

    /**
    * The MemberControllerApi service constructor.
    * @property {module:api/MemberControllerApi}
    */
    MemberControllerApi,

    /**
    * The PolicyControllerApi service constructor.
    * @property {module:api/PolicyControllerApi}
    */
    PolicyControllerApi,

    /**
    * The RoleControllerApi service constructor.
    * @property {module:api/RoleControllerApi}
    */
    RoleControllerApi,

    /**
    * The UnderwritingBenefitsApi service constructor.
    * @property {module:api/UnderwritingBenefitsApi}
    */
    UnderwritingBenefitsApi,

    /**
    * The UnderwritingClientsApi service constructor.
    * @property {module:api/UnderwritingClientsApi}
    */
    UnderwritingClientsApi,

    /**
    * The UnderwritingContractsApi service constructor.
    * @property {module:api/UnderwritingContractsApi}
    */
    UnderwritingContractsApi,

    /**
    * The UserControllerApi service constructor.
    * @property {module:api/UserControllerApi}
    */
    UserControllerApi
};
