/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Assignment model module.
 * @module model/Assignment
 * @version 1.0.0
 */
class Assignment {
    /**
     * Constructs a new <code>Assignment</code>.
     * @alias module:model/Assignment
     * @param startDate {Date} 
     * @param endDate {Date} 
     */
    constructor(startDate, endDate) { 
        
        Assignment.initialize(this, startDate, endDate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, startDate, endDate) { 
        obj['start_date'] = startDate;
        obj['end_date'] = endDate;
    }

    /**
     * Constructs a <code>Assignment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Assignment} obj Optional instance to populate.
     * @return {module:model/Assignment} The populated <code>Assignment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Assignment();

            if (data.hasOwnProperty('role_id')) {
                obj['role_id'] = ApiClient.convertToType(data['role_id'], 'String');
            }
            if (data.hasOwnProperty('group_id')) {
                obj['group_id'] = ApiClient.convertToType(data['group_id'], 'String');
            }
            if (data.hasOwnProperty('start_date')) {
                obj['start_date'] = ApiClient.convertToType(data['start_date'], 'Date');
            }
            if (data.hasOwnProperty('end_date')) {
                obj['end_date'] = ApiClient.convertToType(data['end_date'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} role_id
 */
Assignment.prototype['role_id'] = undefined;

/**
 * @member {String} group_id
 */
Assignment.prototype['group_id'] = undefined;

/**
 * @member {Date} start_date
 */
Assignment.prototype['start_date'] = undefined;

/**
 * @member {Date} end_date
 */
Assignment.prototype['end_date'] = undefined;






export default Assignment;

