/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BasebenefitplansRevisionsFields model module.
 * @module model/BasebenefitplansRevisionsFields
 * @version 1.0.0
 */
class BasebenefitplansRevisionsFields {
    /**
     * Constructs a new <code>BasebenefitplansRevisionsFields</code>.
     * @alias module:model/BasebenefitplansRevisionsFields
     */
    constructor() { 
        
        BasebenefitplansRevisionsFields.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BasebenefitplansRevisionsFields</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BasebenefitplansRevisionsFields} obj Optional instance to populate.
     * @return {module:model/BasebenefitplansRevisionsFields} The populated <code>BasebenefitplansRevisionsFields</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BasebenefitplansRevisionsFields();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'Boolean');
            }
            if (data.hasOwnProperty('delete_dt')) {
                obj['delete_dt'] = ApiClient.convertToType(data['delete_dt'], 'Boolean');
            }
            if (data.hasOwnProperty('document_id')) {
                obj['document_id'] = ApiClient.convertToType(data['document_id'], 'Boolean');
            }
            if (data.hasOwnProperty('op')) {
                obj['op'] = ApiClient.convertToType(data['op'], 'Boolean');
            }
            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], 'Boolean');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'Boolean');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} _id
 */
BasebenefitplansRevisionsFields.prototype['_id'] = undefined;

/**
 * @member {Boolean} delete_dt
 */
BasebenefitplansRevisionsFields.prototype['delete_dt'] = undefined;

/**
 * @member {Boolean} document_id
 */
BasebenefitplansRevisionsFields.prototype['document_id'] = undefined;

/**
 * @member {Boolean} op
 */
BasebenefitplansRevisionsFields.prototype['op'] = undefined;

/**
 * @member {Boolean} from
 */
BasebenefitplansRevisionsFields.prototype['from'] = undefined;

/**
 * @member {Boolean} path
 */
BasebenefitplansRevisionsFields.prototype['path'] = undefined;

/**
 * @member {Boolean} value
 */
BasebenefitplansRevisionsFields.prototype['value'] = undefined;






export default BasebenefitplansRevisionsFields;

