/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BasebenefitplansFields model module.
 * @module model/BasebenefitplansFields
 * @version 1.0.0
 */
class BasebenefitplansFields {
    /**
     * Constructs a new <code>BasebenefitplansFields</code>.
     * @alias module:model/BasebenefitplansFields
     */
    constructor() { 
        
        BasebenefitplansFields.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BasebenefitplansFields</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BasebenefitplansFields} obj Optional instance to populate.
     * @return {module:model/BasebenefitplansFields} The populated <code>BasebenefitplansFields</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BasebenefitplansFields();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'Boolean');
            }
            if (data.hasOwnProperty('delete_dt')) {
                obj['delete_dt'] = ApiClient.convertToType(data['delete_dt'], 'Boolean');
            }
            if (data.hasOwnProperty('base_id')) {
                obj['base_id'] = ApiClient.convertToType(data['base_id'], 'Boolean');
            }
            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'Boolean');
            }
            if (data.hasOwnProperty('tree_id')) {
                obj['tree_id'] = ApiClient.convertToType(data['tree_id'], 'Boolean');
            }
            if (data.hasOwnProperty('tree_path')) {
                obj['tree_path'] = ApiClient.convertToType(data['tree_path'], 'Boolean');
            }
            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'Boolean');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Boolean');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'Boolean');
            }
            if (data.hasOwnProperty('sort_index')) {
                obj['sort_index'] = ApiClient.convertToType(data['sort_index'], 'Boolean');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'Boolean');
            }
            if (data.hasOwnProperty('limits')) {
                obj['limits'] = ApiClient.convertToType(data['limits'], 'Boolean');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Boolean');
            }
            if (data.hasOwnProperty('remarks')) {
                obj['remarks'] = ApiClient.convertToType(data['remarks'], 'Boolean');
            }
            if (data.hasOwnProperty('children')) {
                obj['children'] = ApiClient.convertToType(data['children'], 'Boolean');
            }
            if (data.hasOwnProperty('revisions')) {
                obj['revisions'] = ApiClient.convertToType(data['revisions'], 'Boolean');
            }
            if (data.hasOwnProperty('handler')) {
                obj['handler'] = ApiClient.convertToType(data['handler'], 'Boolean');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], 'Boolean');
            }
            if (data.hasOwnProperty('metadata_schema')) {
                obj['metadata_schema'] = ApiClient.convertToType(data['metadata_schema'], 'Boolean');
            }
            if (data.hasOwnProperty('custom_metadata')) {
                obj['custom_metadata'] = ApiClient.convertToType(data['custom_metadata'], 'Boolean');
            }
            if (data.hasOwnProperty('custom_metadata_schema')) {
                obj['custom_metadata_schema'] = ApiClient.convertToType(data['custom_metadata_schema'], 'Boolean');
            }
            if (data.hasOwnProperty('canAvail')) {
                obj['canAvail'] = ApiClient.convertToType(data['canAvail'], 'Boolean');
            }
            if (data.hasOwnProperty('canCover')) {
                obj['canCover'] = ApiClient.convertToType(data['canCover'], 'Boolean');
            }
            if (data.hasOwnProperty('renderContract')) {
                obj['renderContract'] = ApiClient.convertToType(data['renderContract'], 'Boolean');
            }
            if (data.hasOwnProperty('renderProposal')) {
                obj['renderProposal'] = ApiClient.convertToType(data['renderProposal'], 'Boolean');
            }
            if (data.hasOwnProperty('renderClause')) {
                obj['renderClause'] = ApiClient.convertToType(data['renderClause'], 'Boolean');
            }
            if (data.hasOwnProperty('contract_footer')) {
                obj['contract_footer'] = ApiClient.convertToType(data['contract_footer'], 'Boolean');
            }
            if (data.hasOwnProperty('proposal_footer')) {
                obj['proposal_footer'] = ApiClient.convertToType(data['proposal_footer'], 'Boolean');
            }
            if (data.hasOwnProperty('layers')) {
                obj['layers'] = ApiClient.convertToType(data['layers'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} _id
 */
BasebenefitplansFields.prototype['_id'] = undefined;

/**
 * @member {Boolean} delete_dt
 */
BasebenefitplansFields.prototype['delete_dt'] = undefined;

/**
 * @member {Boolean} base_id
 */
BasebenefitplansFields.prototype['base_id'] = undefined;

/**
 * @member {Boolean} uid
 */
BasebenefitplansFields.prototype['uid'] = undefined;

/**
 * @member {Boolean} tree_id
 */
BasebenefitplansFields.prototype['tree_id'] = undefined;

/**
 * @member {Boolean} tree_path
 */
BasebenefitplansFields.prototype['tree_path'] = undefined;

/**
 * @member {Boolean} level
 */
BasebenefitplansFields.prototype['level'] = undefined;

/**
 * @member {Boolean} name
 */
BasebenefitplansFields.prototype['name'] = undefined;

/**
 * @member {Boolean} code
 */
BasebenefitplansFields.prototype['code'] = undefined;

/**
 * @member {Boolean} type
 */
BasebenefitplansFields.prototype['type'] = undefined;

/**
 * @member {Boolean} sort_index
 */
BasebenefitplansFields.prototype['sort_index'] = undefined;

/**
 * @member {Boolean} description
 */
BasebenefitplansFields.prototype['description'] = undefined;

/**
 * @member {Boolean} limits
 */
BasebenefitplansFields.prototype['limits'] = undefined;

/**
 * @member {Boolean} status
 */
BasebenefitplansFields.prototype['status'] = undefined;

/**
 * @member {Boolean} remarks
 */
BasebenefitplansFields.prototype['remarks'] = undefined;

/**
 * @member {Boolean} children
 */
BasebenefitplansFields.prototype['children'] = undefined;

/**
 * @member {Boolean} revisions
 */
BasebenefitplansFields.prototype['revisions'] = undefined;

/**
 * @member {Boolean} handler
 */
BasebenefitplansFields.prototype['handler'] = undefined;

/**
 * @member {Boolean} metadata
 */
BasebenefitplansFields.prototype['metadata'] = undefined;

/**
 * @member {Boolean} metadata_schema
 */
BasebenefitplansFields.prototype['metadata_schema'] = undefined;

/**
 * @member {Boolean} custom_metadata
 */
BasebenefitplansFields.prototype['custom_metadata'] = undefined;

/**
 * @member {Boolean} custom_metadata_schema
 */
BasebenefitplansFields.prototype['custom_metadata_schema'] = undefined;

/**
 * @member {Boolean} canAvail
 */
BasebenefitplansFields.prototype['canAvail'] = undefined;

/**
 * @member {Boolean} canCover
 */
BasebenefitplansFields.prototype['canCover'] = undefined;

/**
 * @member {Boolean} renderContract
 */
BasebenefitplansFields.prototype['renderContract'] = undefined;

/**
 * @member {Boolean} renderProposal
 */
BasebenefitplansFields.prototype['renderProposal'] = undefined;

/**
 * @member {Boolean} renderClause
 */
BasebenefitplansFields.prototype['renderClause'] = undefined;

/**
 * @member {Boolean} contract_footer
 */
BasebenefitplansFields.prototype['contract_footer'] = undefined;

/**
 * @member {Boolean} proposal_footer
 */
BasebenefitplansFields.prototype['proposal_footer'] = undefined;

/**
 * @member {Boolean} layers
 */
BasebenefitplansFields.prototype['layers'] = undefined;






export default BasebenefitplansFields;

