/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BenefitLayer from './BenefitLayer';

/**
 * The BaseBenefitPlanPartial model module.
 * @module model/BaseBenefitPlanPartial
 * @version 0.1.0
 */
class BaseBenefitPlanPartial {
    /**
     * Constructs a new <code>BaseBenefitPlanPartial</code>.
     * @alias module:model/BaseBenefitPlanPartial
     */
    constructor() { 
        
        BaseBenefitPlanPartial.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BaseBenefitPlanPartial</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BaseBenefitPlanPartial} obj Optional instance to populate.
     * @return {module:model/BaseBenefitPlanPartial} The populated <code>BaseBenefitPlanPartial</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BaseBenefitPlanPartial();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('is_deleted')) {
                obj['is_deleted'] = ApiClient.convertToType(data['is_deleted'], 'Boolean');
            }
            if (data.hasOwnProperty('deleted_at')) {
                obj['deleted_at'] = ApiClient.convertToType(data['deleted_at'], 'Date');
            }
            if (data.hasOwnProperty('base_id')) {
                obj['base_id'] = ApiClient.convertToType(data['base_id'], 'String');
            }
            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('tree_id')) {
                obj['tree_id'] = ApiClient.convertToType(data['tree_id'], 'String');
            }
            if (data.hasOwnProperty('tree_path')) {
                obj['tree_path'] = ApiClient.convertToType(data['tree_path'], ['String']);
            }
            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('sort_index')) {
                obj['sort_index'] = ApiClient.convertToType(data['sort_index'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('limits')) {
                obj['limits'] = ApiClient.convertToType(data['limits'], [BenefitLayer]);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('remarks')) {
                obj['remarks'] = ApiClient.convertToType(data['remarks'], 'String');
            }
            if (data.hasOwnProperty('children')) {
                obj['children'] = ApiClient.convertToType(data['children'], [Object]);
            }
            if (data.hasOwnProperty('revisions')) {
                obj['revisions'] = ApiClient.convertToType(data['revisions'], [Object]);
            }
            if (data.hasOwnProperty('schema')) {
                obj['schema'] = ApiClient.convertToType(data['schema'], Object);
            }
            if (data.hasOwnProperty('canAvail')) {
                obj['canAvail'] = ApiClient.convertToType(data['canAvail'], 'String');
            }
            if (data.hasOwnProperty('canCover')) {
                obj['canCover'] = ApiClient.convertToType(data['canCover'], 'String');
            }
            if (data.hasOwnProperty('renderContract')) {
                obj['renderContract'] = ApiClient.convertToType(data['renderContract'], 'String');
            }
            if (data.hasOwnProperty('renderProposal')) {
                obj['renderProposal'] = ApiClient.convertToType(data['renderProposal'], 'String');
            }
            if (data.hasOwnProperty('renderClause')) {
                obj['renderClause'] = ApiClient.convertToType(data['renderClause'], 'String');
            }
            if (data.hasOwnProperty('contract_footer')) {
                obj['contract_footer'] = ApiClient.convertToType(data['contract_footer'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
BaseBenefitPlanPartial.prototype['_id'] = undefined;

/**
 * @member {Boolean} is_deleted
 */
BaseBenefitPlanPartial.prototype['is_deleted'] = undefined;

/**
 * @member {Date} deleted_at
 */
BaseBenefitPlanPartial.prototype['deleted_at'] = undefined;

/**
 * A code to distinguish a node within a benefits library. A.K.A. benefit ID.
 * @member {String} base_id
 */
BaseBenefitPlanPartial.prototype['base_id'] = undefined;

/**
 * A unique code for an instance of a benefit node, can be used as CHILD_ID or PARENT_ID
 * @member {String} uid
 */
BaseBenefitPlanPartial.prototype['uid'] = undefined;

/**
 * A code to determine a node within a benefits tree
 * @member {String} tree_id
 */
BaseBenefitPlanPartial.prototype['tree_id'] = undefined;

/**
 * @member {Array.<String>} tree_path
 */
BaseBenefitPlanPartial.prototype['tree_path'] = undefined;

/**
 * @member {Number} level
 */
BaseBenefitPlanPartial.prototype['level'] = undefined;

/**
 * @member {String} name
 */
BaseBenefitPlanPartial.prototype['name'] = undefined;

/**
 * @member {String} code
 */
BaseBenefitPlanPartial.prototype['code'] = undefined;

/**
 * @member {String} type
 */
BaseBenefitPlanPartial.prototype['type'] = undefined;

/**
 * @member {Number} sort_index
 */
BaseBenefitPlanPartial.prototype['sort_index'] = undefined;

/**
 * @member {String} description
 */
BaseBenefitPlanPartial.prototype['description'] = undefined;

/**
 * @member {Array.<module:model/BenefitLayer>} limits
 */
BaseBenefitPlanPartial.prototype['limits'] = undefined;

/**
 * @member {String} status
 */
BaseBenefitPlanPartial.prototype['status'] = undefined;

/**
 * @member {String} remarks
 */
BaseBenefitPlanPartial.prototype['remarks'] = undefined;

/**
 * @member {Array.<Object>} children
 */
BaseBenefitPlanPartial.prototype['children'] = undefined;

/**
 * @member {Array.<Object>} revisions
 */
BaseBenefitPlanPartial.prototype['revisions'] = undefined;

/**
 * @member {Object} schema
 */
BaseBenefitPlanPartial.prototype['schema'] = undefined;

/**
 * @member {String} canAvail
 */
BaseBenefitPlanPartial.prototype['canAvail'] = undefined;

/**
 * @member {String} canCover
 */
BaseBenefitPlanPartial.prototype['canCover'] = undefined;

/**
 * @member {String} renderContract
 */
BaseBenefitPlanPartial.prototype['renderContract'] = undefined;

/**
 * @member {String} renderProposal
 */
BaseBenefitPlanPartial.prototype['renderProposal'] = undefined;

/**
 * @member {String} renderClause
 */
BaseBenefitPlanPartial.prototype['renderClause'] = undefined;

/**
 * @member {String} contract_footer
 */
BaseBenefitPlanPartial.prototype['contract_footer'] = undefined;






export default BaseBenefitPlanPartial;

