/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BenefitComment model module.
 * @module model/BenefitComment
 * @version 1.0.0
 */
class BenefitComment {
    /**
     * Constructs a new <code>BenefitComment</code>.
     * Comments for proposals
     * @alias module:model/BenefitComment
     * @param documentId {Object} 
     * @param authorId {Object} 
     * @param description {String} 
     * @param status {String} 
     */
    constructor(documentId, authorId, description, status) { 
        
        BenefitComment.initialize(this, documentId, authorId, description, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, documentId, authorId, description, status) { 
        obj['document_id'] = documentId;
        obj['author_id'] = authorId;
        obj['description'] = description;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>BenefitComment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BenefitComment} obj Optional instance to populate.
     * @return {module:model/BenefitComment} The populated <code>BenefitComment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BenefitComment();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('delete_dt')) {
                obj['delete_dt'] = ApiClient.convertToType(data['delete_dt'], 'Date');
            }
            if (data.hasOwnProperty('document_id')) {
                obj['document_id'] = ApiClient.convertToType(data['document_id'], Object);
            }
            if (data.hasOwnProperty('author_id')) {
                obj['author_id'] = ApiClient.convertToType(data['author_id'], Object);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Primary key of a document in a MongoDB collection.
 * @member {String} _id
 */
BenefitComment.prototype['_id'] = undefined;

/**
 * Date an item is deleted. Null/undefined value means the item is not yet deleted.
 * @member {Date} delete_dt
 */
BenefitComment.prototype['delete_dt'] = undefined;

/**
 * @member {Object} document_id
 */
BenefitComment.prototype['document_id'] = undefined;

/**
 * @member {Object} author_id
 */
BenefitComment.prototype['author_id'] = undefined;

/**
 * @member {String} description
 */
BenefitComment.prototype['description'] = undefined;

/**
 * @member {String} status
 */
BenefitComment.prototype['status'] = undefined;






export default BenefitComment;

