/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CanAvailRequest model module.
 * @module model/CanAvailRequest
 * @version 1.0.0
 */
class CanAvailRequest {
    /**
     * Constructs a new <code>CanAvailRequest</code>.
     * @alias module:model/CanAvailRequest
     */
    constructor() { 
        
        CanAvailRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CanAvailRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CanAvailRequest} obj Optional instance to populate.
     * @return {module:model/CanAvailRequest} The populated <code>CanAvailRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CanAvailRequest();

            if (data.hasOwnProperty('facility')) {
                obj['facility'] = ApiClient.convertToType(data['facility'], 'String');
            }
            if (data.hasOwnProperty('procedure')) {
                obj['procedure'] = ApiClient.convertToType(data['procedure'], 'String');
            }
            if (data.hasOwnProperty('diagnosis')) {
                obj['diagnosis'] = ApiClient.convertToType(data['diagnosis'], 'String');
            }
            if (data.hasOwnProperty('physician')) {
                obj['physician'] = ApiClient.convertToType(data['physician'], 'String');
            }
            if (data.hasOwnProperty('room')) {
                obj['room'] = ApiClient.convertToType(data['room'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} facility
 */
CanAvailRequest.prototype['facility'] = undefined;

/**
 * @member {String} procedure
 */
CanAvailRequest.prototype['procedure'] = undefined;

/**
 * @member {String} diagnosis
 */
CanAvailRequest.prototype['diagnosis'] = undefined;

/**
 * @member {String} physician
 */
CanAvailRequest.prototype['physician'] = undefined;

/**
 * @member {String} room
 */
CanAvailRequest.prototype['room'] = undefined;






export default CanAvailRequest;

