/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CanAvailResponseCoverage from './CanAvailResponseCoverage';

/**
 * The CanAvailResponse model module.
 * @module model/CanAvailResponse
 * @version 1.0.0
 */
class CanAvailResponse {
    /**
     * Constructs a new <code>CanAvailResponse</code>.
     * @alias module:model/CanAvailResponse
     * @param coverage {Array.<module:model/CanAvailResponseCoverage>} 
     */
    constructor(coverage) { 
        
        CanAvailResponse.initialize(this, coverage);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, coverage) { 
        obj['coverage'] = coverage;
    }

    /**
     * Constructs a <code>CanAvailResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CanAvailResponse} obj Optional instance to populate.
     * @return {module:model/CanAvailResponse} The populated <code>CanAvailResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CanAvailResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('coverage')) {
                obj['coverage'] = ApiClient.convertToType(data['coverage'], [CanAvailResponseCoverage]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
CanAvailResponse.prototype['id'] = undefined;

/**
 * @member {Array.<module:model/CanAvailResponseCoverage>} coverage
 */
CanAvailResponse.prototype['coverage'] = undefined;






export default CanAvailResponse;

