/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ContactNumber model module.
 * @module model/ContactNumber
 * @version 1.0.0
 */
class ContactNumber {
    /**
     * Constructs a new <code>ContactNumber</code>.
     * Contact numbers
     * @alias module:model/ContactNumber
     * @param no {String} Telephone number / Trunk line
     */
    constructor(no) { 
        
        ContactNumber.initialize(this, no);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, no) { 
        obj['no'] = no;
    }

    /**
     * Constructs a <code>ContactNumber</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContactNumber} obj Optional instance to populate.
     * @return {module:model/ContactNumber} The populated <code>ContactNumber</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContactNumber();

            if (data.hasOwnProperty('no')) {
                obj['no'] = ApiClient.convertToType(data['no'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Telephone number / Trunk line
 * @member {String} no
 */
ContactNumber.prototype['no'] = undefined;






export default ContactNumber;

