/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ContactAddress model module.
 * @module model/ContactAddress
 * @version 1.0.0
 */
class ContactAddress {
    /**
     * Constructs a new <code>ContactAddress</code>.
     * Main office address
     * @alias module:model/ContactAddress
     * @param floor {Number} Floor number
     * @param unit {String} Unit
     * @param bldgNo {String} Building number
     * @param bldgName {String} Building name
     * @param street {String} Street name
     * @param brgy {String} Barangay
     * @param city {String} City
     * @param region {String} Region
     * @param zipCode {String} ZIP code
     */
    constructor(floor, unit, bldgNo, bldgName, street, brgy, city, region, zipCode) { 
        
        ContactAddress.initialize(this, floor, unit, bldgNo, bldgName, street, brgy, city, region, zipCode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, floor, unit, bldgNo, bldgName, street, brgy, city, region, zipCode) { 
        obj['floor'] = floor;
        obj['unit'] = unit;
        obj['bldg_no'] = bldgNo;
        obj['bldg_name'] = bldgName;
        obj['street'] = street;
        obj['brgy'] = brgy;
        obj['city'] = city;
        obj['region'] = region;
        obj['zip_code'] = zipCode;
    }

    /**
     * Constructs a <code>ContactAddress</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContactAddress} obj Optional instance to populate.
     * @return {module:model/ContactAddress} The populated <code>ContactAddress</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContactAddress();

            if (data.hasOwnProperty('floor')) {
                obj['floor'] = ApiClient.convertToType(data['floor'], 'Number');
            }
            if (data.hasOwnProperty('unit')) {
                obj['unit'] = ApiClient.convertToType(data['unit'], 'String');
            }
            if (data.hasOwnProperty('bldg_no')) {
                obj['bldg_no'] = ApiClient.convertToType(data['bldg_no'], 'String');
            }
            if (data.hasOwnProperty('bldg_name')) {
                obj['bldg_name'] = ApiClient.convertToType(data['bldg_name'], 'String');
            }
            if (data.hasOwnProperty('street')) {
                obj['street'] = ApiClient.convertToType(data['street'], 'String');
            }
            if (data.hasOwnProperty('brgy')) {
                obj['brgy'] = ApiClient.convertToType(data['brgy'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('region')) {
                obj['region'] = ApiClient.convertToType(data['region'], 'String');
            }
            if (data.hasOwnProperty('zip_code')) {
                obj['zip_code'] = ApiClient.convertToType(data['zip_code'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Floor number
 * @member {Number} floor
 */
ContactAddress.prototype['floor'] = undefined;

/**
 * Unit
 * @member {String} unit
 */
ContactAddress.prototype['unit'] = undefined;

/**
 * Building number
 * @member {String} bldg_no
 */
ContactAddress.prototype['bldg_no'] = undefined;

/**
 * Building name
 * @member {String} bldg_name
 */
ContactAddress.prototype['bldg_name'] = undefined;

/**
 * Street name
 * @member {String} street
 */
ContactAddress.prototype['street'] = undefined;

/**
 * Barangay
 * @member {String} brgy
 */
ContactAddress.prototype['brgy'] = undefined;

/**
 * City
 * @member {String} city
 */
ContactAddress.prototype['city'] = undefined;

/**
 * Region
 * @member {String} region
 */
ContactAddress.prototype['region'] = undefined;

/**
 * ZIP code
 * @member {String} zip_code
 */
ContactAddress.prototype['zip_code'] = undefined;






export default ContactAddress;

