/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Cpt model module.
 * @module model/Cpt
 * @version 1.0.0
 */
class Cpt {
    /**
     * Constructs a new <code>Cpt</code>.
     * @alias module:model/Cpt
     * @param code {String} 
     * @param label {String} 
     */
    constructor(code, label) { 
        
        Cpt.initialize(this, code, label);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code, label) { 
        obj['code'] = code;
        obj['label'] = label;
    }

    /**
     * Constructs a <code>Cpt</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Cpt} obj Optional instance to populate.
     * @return {module:model/Cpt} The populated <code>Cpt</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Cpt();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Cpt.prototype['_id'] = undefined;

/**
 * @member {String} code
 */
Cpt.prototype['code'] = undefined;

/**
 * @member {String} label
 */
Cpt.prototype['label'] = undefined;






export default Cpt;

