/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CptsFields model module.
 * @module model/CptsFields
 * @version 1.0.0
 */
class CptsFields {
    /**
     * Constructs a new <code>CptsFields</code>.
     * @alias module:model/CptsFields
     */
    constructor() { 
        
        CptsFields.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CptsFields</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CptsFields} obj Optional instance to populate.
     * @return {module:model/CptsFields} The populated <code>CptsFields</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CptsFields();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'Boolean');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Boolean');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} _id
 */
CptsFields.prototype['_id'] = undefined;

/**
 * @member {Boolean} code
 */
CptsFields.prototype['code'] = undefined;

/**
 * @member {Boolean} label
 */
CptsFields.prototype['label'] = undefined;






export default CptsFields;

