/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BenefitPlan from './BenefitPlan';
import Client from './Client';

/**
 * The CreateProposalRequest model module.
 * @module model/CreateProposalRequest
 * @version 1.0.0
 */
class CreateProposalRequest {
    /**
     * Constructs a new <code>CreateProposalRequest</code>.
     * @alias module:model/CreateProposalRequest
     * @param nodes {Array.<module:model/BenefitPlan>} 
     */
    constructor(nodes) { 
        
        CreateProposalRequest.initialize(this, nodes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, nodes) { 
        obj['nodes'] = nodes;
    }

    /**
     * Constructs a <code>CreateProposalRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateProposalRequest} obj Optional instance to populate.
     * @return {module:model/CreateProposalRequest} The populated <code>CreateProposalRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateProposalRequest();

            if (data.hasOwnProperty('client')) {
                obj['client'] = Client.constructFromObject(data['client']);
            }
            if (data.hasOwnProperty('nodes')) {
                obj['nodes'] = ApiClient.convertToType(data['nodes'], [BenefitPlan]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Client} client
 */
CreateProposalRequest.prototype['client'] = undefined;

/**
 * @member {Array.<module:model/BenefitPlan>} nodes
 */
CreateProposalRequest.prototype['nodes'] = undefined;






export default CreateProposalRequest;

