/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DoctorsFields model module.
 * @module model/DoctorsFields
 * @version 1.0.0
 */
class DoctorsFields {
    /**
     * Constructs a new <code>DoctorsFields</code>.
     * @alias module:model/DoctorsFields
     */
    constructor() { 
        
        DoctorsFields.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DoctorsFields</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DoctorsFields} obj Optional instance to populate.
     * @return {module:model/DoctorsFields} The populated <code>DoctorsFields</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DoctorsFields();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'Boolean');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'Boolean');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'Boolean');
            }
            if (data.hasOwnProperty('middle_name')) {
                obj['middle_name'] = ApiClient.convertToType(data['middle_name'], 'Boolean');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'Boolean');
            }
            if (data.hasOwnProperty('gender')) {
                obj['gender'] = ApiClient.convertToType(data['gender'], 'Boolean');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'Boolean');
            }
            if (data.hasOwnProperty('specializations')) {
                obj['specializations'] = ApiClient.convertToType(data['specializations'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} _id
 */
DoctorsFields.prototype['_id'] = undefined;

/**
 * @member {Boolean} type
 */
DoctorsFields.prototype['type'] = undefined;

/**
 * @member {Boolean} first_name
 */
DoctorsFields.prototype['first_name'] = undefined;

/**
 * @member {Boolean} middle_name
 */
DoctorsFields.prototype['middle_name'] = undefined;

/**
 * @member {Boolean} last_name
 */
DoctorsFields.prototype['last_name'] = undefined;

/**
 * @member {Boolean} gender
 */
DoctorsFields.prototype['gender'] = undefined;

/**
 * @member {Boolean} address
 */
DoctorsFields.prototype['address'] = undefined;

/**
 * @member {Boolean} specializations
 */
DoctorsFields.prototype['specializations'] = undefined;






export default DoctorsFields;

