/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Doctor model module.
 * @module model/Doctor
 * @version 1.0.0
 */
class Doctor {
    /**
     * Constructs a new <code>Doctor</code>.
     * @alias module:model/Doctor
     * @param type {String} 
     * @param firstName {String} 
     * @param lastName {String} 
     */
    constructor(type, firstName, lastName) { 
        
        Doctor.initialize(this, type, firstName, lastName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, firstName, lastName) { 
        obj['type'] = type;
        obj['first_name'] = firstName;
        obj['last_name'] = lastName;
    }

    /**
     * Constructs a <code>Doctor</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Doctor} obj Optional instance to populate.
     * @return {module:model/Doctor} The populated <code>Doctor</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Doctor();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('middle_name')) {
                obj['middle_name'] = ApiClient.convertToType(data['middle_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('gender')) {
                obj['gender'] = ApiClient.convertToType(data['gender'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], Object);
            }
            if (data.hasOwnProperty('specializations')) {
                obj['specializations'] = ApiClient.convertToType(data['specializations'], [Object]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Doctor.prototype['_id'] = undefined;

/**
 * @member {String} type
 */
Doctor.prototype['type'] = undefined;

/**
 * @member {String} first_name
 */
Doctor.prototype['first_name'] = undefined;

/**
 * @member {String} middle_name
 */
Doctor.prototype['middle_name'] = undefined;

/**
 * @member {String} last_name
 */
Doctor.prototype['last_name'] = undefined;

/**
 * @member {String} gender
 */
Doctor.prototype['gender'] = undefined;

/**
 * @member {Object} address
 */
Doctor.prototype['address'] = undefined;

/**
 * @member {Array.<Object>} specializations
 */
Doctor.prototype['specializations'] = undefined;






export default Doctor;

