/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FacilitiesFields model module.
 * @module model/FacilitiesFields
 * @version 1.0.0
 */
class FacilitiesFields {
    /**
     * Constructs a new <code>FacilitiesFields</code>.
     * @alias module:model/FacilitiesFields
     */
    constructor() { 
        
        FacilitiesFields.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FacilitiesFields</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FacilitiesFields} obj Optional instance to populate.
     * @return {module:model/FacilitiesFields} The populated <code>FacilitiesFields</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FacilitiesFields();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'Boolean');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'Boolean');
            }
            if (data.hasOwnProperty('services')) {
                obj['services'] = ApiClient.convertToType(data['services'], 'Boolean');
            }
            if (data.hasOwnProperty('doctors')) {
                obj['doctors'] = ApiClient.convertToType(data['doctors'], 'Boolean');
            }
            if (data.hasOwnProperty('rooms')) {
                obj['rooms'] = ApiClient.convertToType(data['rooms'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} _id
 */
FacilitiesFields.prototype['_id'] = undefined;

/**
 * @member {Boolean} type
 */
FacilitiesFields.prototype['type'] = undefined;

/**
 * @member {Boolean} name
 */
FacilitiesFields.prototype['name'] = undefined;

/**
 * @member {Boolean} services
 */
FacilitiesFields.prototype['services'] = undefined;

/**
 * @member {Boolean} doctors
 */
FacilitiesFields.prototype['doctors'] = undefined;

/**
 * @member {Boolean} rooms
 */
FacilitiesFields.prototype['rooms'] = undefined;






export default FacilitiesFields;

