/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FacilityPartial model module.
 * @module model/FacilityPartial
 * @version 1.0.0
 */
class FacilityPartial {
    /**
     * Constructs a new <code>FacilityPartial</code>.
     * @alias module:model/FacilityPartial
     */
    constructor() { 
        
        FacilityPartial.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FacilityPartial</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FacilityPartial} obj Optional instance to populate.
     * @return {module:model/FacilityPartial} The populated <code>FacilityPartial</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FacilityPartial();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('services')) {
                obj['services'] = ApiClient.convertToType(data['services'], [Object]);
            }
            if (data.hasOwnProperty('doctors')) {
                obj['doctors'] = ApiClient.convertToType(data['doctors'], [Object]);
            }
            if (data.hasOwnProperty('rooms')) {
                obj['rooms'] = ApiClient.convertToType(data['rooms'], [Object]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
FacilityPartial.prototype['_id'] = undefined;

/**
 * @member {String} type
 */
FacilityPartial.prototype['type'] = undefined;

/**
 * @member {String} name
 */
FacilityPartial.prototype['name'] = undefined;

/**
 * @member {Array.<Object>} services
 */
FacilityPartial.prototype['services'] = undefined;

/**
 * @member {Array.<Object>} doctors
 */
FacilityPartial.prototype['doctors'] = undefined;

/**
 * @member {Array.<Object>} rooms
 */
FacilityPartial.prototype['rooms'] = undefined;






export default FacilityPartial;

