/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UsersFields model module.
 * @module model/UsersFields
 * @version 1.0.0
 */
class UsersFields {
    /**
     * Constructs a new <code>UsersFields</code>.
     * @alias module:model/UsersFields
     */
    constructor() { 
        
        UsersFields.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UsersFields</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsersFields} obj Optional instance to populate.
     * @return {module:model/UsersFields} The populated <code>UsersFields</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersFields();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'Boolean');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'Boolean');
            }
            if (data.hasOwnProperty('middle_name')) {
                obj['middle_name'] = ApiClient.convertToType(data['middle_name'], 'Boolean');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'Boolean');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'Boolean');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'Boolean');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'Boolean');
            }
            if (data.hasOwnProperty('assingments')) {
                obj['assingments'] = ApiClient.convertToType(data['assingments'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} _id
 */
UsersFields.prototype['_id'] = undefined;

/**
 * @member {Boolean} last_name
 */
UsersFields.prototype['last_name'] = undefined;

/**
 * @member {Boolean} middle_name
 */
UsersFields.prototype['middle_name'] = undefined;

/**
 * @member {Boolean} first_name
 */
UsersFields.prototype['first_name'] = undefined;

/**
 * @member {Boolean} title
 */
UsersFields.prototype['title'] = undefined;

/**
 * @member {Boolean} username
 */
UsersFields.prototype['username'] = undefined;

/**
 * @member {Boolean} password
 */
UsersFields.prototype['password'] = undefined;

/**
 * @member {Boolean} assingments
 */
UsersFields.prototype['assingments'] = undefined;






export default UsersFields;

