/**
 * HIMS API - Client
 * HIMS API Defintions for Client Subsystem
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hims-info@veridata.com.ph
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.@HimsApi);
  }
}(this, function(expect, @HimsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new @HimsApi.CanAvailResponseCoverage();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CanAvailResponseCoverage', function() {
    it('should create an instance of CanAvailResponseCoverage', function() {
      // uncomment below and update the code to test CanAvailResponseCoverage
      //var instane = new @HimsApi.CanAvailResponseCoverage();
      //expect(instance).to.be.a(@HimsApi.CanAvailResponseCoverage);
    });

    it('should have the property benefitId (base name: "benefit_id")', function() {
      // uncomment below and update the code to test the property benefitId
      //var instane = new @HimsApi.CanAvailResponseCoverage();
      //expect(instance).to.be();
    });

    it('should have the property parentId (base name: "parent_id")', function() {
      // uncomment below and update the code to test the property parentId
      //var instane = new @HimsApi.CanAvailResponseCoverage();
      //expect(instance).to.be();
    });

    it('should have the property parentName (base name: "parent_name")', function() {
      // uncomment below and update the code to test the property parentName
      //var instane = new @HimsApi.CanAvailResponseCoverage();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new @HimsApi.CanAvailResponseCoverage();
      //expect(instance).to.be();
    });

    it('should have the property covered (base name: "covered")', function() {
      // uncomment below and update the code to test the property covered
      //var instane = new @HimsApi.CanAvailResponseCoverage();
      //expect(instance).to.be();
    });

    it('should have the property notCovered (base name: "not_covered")', function() {
      // uncomment below and update the code to test the property notCovered
      //var instane = new @HimsApi.CanAvailResponseCoverage();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instane = new @HimsApi.CanAvailResponseCoverage();
      //expect(instance).to.be();
    });

  });

}));
